Fixed testing in python2 vs. python3

diff --git a/bin/test-style b/bin/test-style
--- a/bin/test-style
+++ b/bin/test-style
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Regression test
+# Test Python coding style
 #
 # Andrew DeOrio <awdeorio@umich.edu>
 
@@ -14,6 +14,17 @@ SRC="\
 # Stop on errors
 set -e
 set -o pipefail
+
+# Check for virtual env
+if [ -z "${VIRTUAL_ENV}" ]; then
+  echo "Error: did you forget to activate a virtual environment?  Try:"
+  echo "$ python3 -m venv env"
+  echo "$ source env/bin/activate"
+  echo "  OR"
+  echo "$ virtualenv env && source env/bin/activate  # python2"
+  echo "$ source env/bin/activate"
+  exit 1
+fi
 
 # Make sure tools are installed locally
 if ! which pylint | grep -q env &> /dev/null ||
@@ -30,6 +41,3 @@ set -x
 pycodestyle ${SRC}
 pydocstyle ${SRC}
 pylint --reports=n ${SRC}
-
-# Unit tests
-python -m unittest discover tests
